{
  "hash": "a7456f00401201028c94dadad90114ce",
  "result": {
    "markdown": "---\ntitle: \"Pemeriksaan dan Pengujian Asumsi ANOVA dengan R\"\ndate: 11-19-2021\nauthor: Gerry Alfa Dito\ncategories: \n      - Compare Means\n      - Analysis of Experiments Data\ndraft: false\nimage: post-image.jpg\n---\n\n\n\n## Package\n\nInstall package berikut jika belum ada\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"tidyverse\")\ninstall.packages(\"broom\")\ninstall.packages(\"performance\")\ninstall.packages(\"see\")\ninstall.packages(\"car\")\ninstall.packages(\"fbasics\")\ninstall.packages(\"ggpubr\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(performance)\nlibrary(see)\nlibrary(car)\nlibrary(broom)\nlibrary(fBasics)\nlibrary(ggpubr)\n```\n:::\n\n\n\n## Data\n\nSebuah percobaan dilakukan untuk menyelidiki efektivitas lima bahan isolasi (insulating materials). Bahan Isolasi merupakan bahan yang tidak dapat mengalirkan arus listrik atau panas. Empat sampel dari setiap bahan yang diuji padategangan tinggi untuk mempercepat waktu kegagalan (failure time).Waktu kegagalan menunjukkan waktu saat bahan isolasi tidak bisa lagi menghambat arus listrik atau panas. Waktu kegagalan (dalam menit) ditunjukkan di bawah ini: \n\n![](Isolating Material Table.png)\n\n## Import Data ke dalam R\n\nUntuk import data ke R kita bisa langsung menuliskan data nya di R dengan sintaks seperti dibawah ini\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbahan_isolasi <- read.table(header = TRUE,\n                            text=\"Bahan WaktuKegagalan\n                                  A 110\n                                  A 157\n                                  A 194\n                                  A 178\n                                  B 1\n                                  B 2\n                                  B 4\n                                  B 18\n                                  C 880\n                                  C 1256\n                                  C 5276\n                                  C 4355\n                                  D 495\n                                  D 7040\n                                  D 5307\n                                  D 10050\n                                  E 7\n                                  E 5\n                                  E 29\n                                  E 2\n                                  \")\nbahan_isolasi\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Bahan WaktuKegagalan\n1      A            110\n2      A            157\n3      A            194\n4      A            178\n5      B              1\n6      B              2\n7      B              4\n8      B             18\n9      C            880\n10     C           1256\n11     C           5276\n12     C           4355\n13     D            495\n14     D           7040\n15     D           5307\n16     D          10050\n17     E              7\n18     E              5\n19     E             29\n20     E              2\n```\n:::\n:::\n\n\n\n\n\n## Analysis of Variance (ANOVA)\n\nHipotesis yang diuji pada kasus ini adalah\n\n$$\n\\begin{aligned}\nH_{0} &: \\text{rerata waktu kegagalan sama untuk semua jenis bahan} \\\\\nH_{1} &: \\text{terdapat minimal sepasang jenis bahan yang memiliki rerata waktu kegagalan tidak sama}\n\\end{aligned}\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova1 <- aov(WaktuKegagalan ~ Bahan,data = bahan_isolasi)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(anova1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 6\n  term         df      sumsq    meansq statistic  p.value\n  <chr>     <dbl>      <dbl>     <dbl>     <dbl>    <dbl>\n1 Bahan         4 103191489. 25797872.      6.19  0.00379\n2 Residuals    15  62505657   4167044.     NA    NA      \n```\n:::\n:::\n\n\nkarena p-value yang dihasilkan dari uji ANOVA kurang dari 0.05 maka cukup bukti untuk mengakatakan bahwa $H_{0}$ ditolak atau dengan kata lain **terdapat minimal sepasang jenis bahan yang memiliki rata-rata waktu kegagalan tidak sama**\n\n## Pemeriksaan Asumsi ANOVA\n\nPemeriksaan asumsi ANOVA dilakukan pada residual nya. Untuk mengeluarkan residualnya bisa menggunakan sintaks dibawah ini\n\n\n::: {.cell}\n\n```{.r .cell-code}\naug1 <- augment(anova1)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naug1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 20 × 8\n   WaktuKegagalan Bahan .fitted   .resid  .hat .sigma     .cooksd .std.resid\n            <int> <chr>   <dbl>    <dbl> <dbl>  <dbl>       <dbl>      <dbl>\n 1            110 A      160.     -49.7   0.25  2113. 0.0000528     -0.0281 \n 2            157 A      160.      -2.75  0.25  2113. 0.000000161   -0.00156\n 3            194 A      160.      34.3   0.25  2113. 0.0000250      0.0194 \n 4            178 A      160.      18.3   0.25  2113. 0.00000710     0.0103 \n 5              1 B        6.25    -5.25  0.25  2113. 0.000000588   -0.00297\n 6              2 B        6.25    -4.25  0.25  2113. 0.000000385   -0.00240\n 7              4 B        6.25    -2.25  0.25  2113. 0.000000108   -0.00127\n 8             18 B        6.25    11.7   0.25  2113. 0.00000295     0.00665\n 9            880 C     2942.   -2062.    0.25  2015. 0.0907        -1.17   \n10           1256 C     2942.   -1686.    0.25  2048. 0.0606        -0.954  \n11           5276 C     2942.    2334.    0.25  1986. 0.116          1.32   \n12           4355 C     2942.    1413.    0.25  2067. 0.0426         0.799  \n13            495 D     5723    -5228     0.25  1364. 0.583         -2.96   \n14           7040 D     5723     1317.    0.25  2074. 0.0370         0.745  \n15           5307 D     5723     -416.    0.25  2109. 0.00369       -0.235  \n16          10050 D     5723     4327     0.25  1638. 0.399          2.45   \n17              7 E       10.8     -3.75  0.25  2113. 0.000000300   -0.00212\n18              5 E       10.8     -5.75  0.25  2113. 0.000000705   -0.00325\n19             29 E       10.8     18.2   0.25  2113. 0.00000710     0.0103 \n20              2 E       10.8     -8.75  0.25  2113. 0.00000163    -0.00495\n```\n:::\n:::\n\n\n\n### Normalitas (Residual Menyebar Normal)\n\nPemeriksaan Normalitas bisa dilakukan dengan menggunakan grafik atau uji hipotesis.\n\n\n#### Grafik\n\nuntuk menampilkan grafik dibawah ini terlebih dahulu harus memanggil package `performance` dan `see`\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(check_normality(x = anova1),type=\"qq\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nDari grafik ini, terdapat beberapa titik residual yang tidak mengikuti pola garis  maka diduga bahwa asumsi normalitas tidak dipenuhi.\n\n#### Uji Hipotesis\n\nHipotesis yang diuji untuk pemeriksaan normalitas adalah\n\n$$\n\\begin{aligned}\nH_{0} &: \\text{galat menyebar normal} \\\\\nH_{1} &: \\text{galat tidak menyebar normal}\n\\end{aligned}\n$$\n\nUji Normalitas bisa dilakukan dengan beberapa metode pengujian. Untuk itu, akan dibuat fungsi R agar dapat menjalankan metode-metode pengujian tersebut. Fungsi R ini tidak perlu dipahami secara serius karena dapat digunakan untuk berbagai kondisi data. Fungsi R buatan ini sangat bergantung pada package `fbasics`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## fungsi R buatan\n\nnormal_test <- function(data,variable){\n  ad_stat <- adTest(\n    data %>% \n      pull(variable)\n    )@test$statistic\n  ks_stat <- ksnormTest(\n    data %>% \n      pull(variable)\n    )@test$statistic\n  jb_stat <- jarqueberaTest(\n    data %>% \n      pull(variable)\n    )@test$statistic\n  \n  shapiro_stat <- shapiroTest(\n    data %>% \n      pull(variable)\n    )@test$statistic\n  \n  ad_p.value <- adTest(\n    data %>% \n      pull(variable)\n    )@test$p.value\n  ks_p.value <- ksnormTest(\n    data %>% \n      pull(variable)\n    )@test$p.value\n  jb_p.value <- jarqueberaTest(\n    data %>% \n      pull(variable)\n    )@test$p.value\n  \n  shapiro_p.value <- shapiroTest(\n    data %>% \n      pull(variable)\n    )@test$p.value\n  \n  all_stats <- data.frame(statistic=c(ad_stat,                                  ks_stat[1],\n                        jb_stat,\n                        shapiro_stat),\n                        p.value=c(\n                        ad_p.value,                              ks_p.value[1],\n                        jb_p.value,\n                        shapiro_p.value\n                        )) %>% \n    mutate(across(where(is.numeric),~ round(.x,3))) %>% \n    mutate(name=c(\"Anderson-Darling\",\n                    \"Kolmogorov-Smirnov\",\n                    \"Shapiro-Wilk\",\n                    \"Jarque-Bera\")) %>% \n    relocate(name) \n    \n  \n  rownames(all_stats) <- NULL\n  return(all_stats)\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnormal_test(data = aug1,\n            variable = \".resid\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                name statistic p.value\n1   Anderson-Darling     1.959   0.000\n2 Kolmogorov-Smirnov     0.588   0.000\n3       Shapiro-Wilk     8.113   0.017\n4        Jarque-Bera     0.809   0.001\n```\n:::\n:::\n\n\n\nkarena p-value yang dihasilkan dari uji normalitas kurang dari 0.05 maka $H_{0}$ ditolak atau dengan kata lain **residual tidak menyebar normal**\n\n### Homogenitas\n\nPemeriksaan Homogenitas bisa dilakukan dengan menggunakan grafik atau uji hipotesis.\n\n\n#### Grafik\n\nuntuk menampilkan grafik dibawah ini menggunakan package `ggpubr` \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggscatter(data = aug1,\n                  x=\".fitted\",\n                  y=\".resid\")+\n  geom_hline(aes(yintercept=0)) +\n  theme_lucid()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\nDari grafik ini, terdapat pola berbentuk corong (funnel shape) maka diduga bahwa asumsi homogenitas tidak dipenuhi.\n\n#### Uji Hipotesis\n\nHipotesis yang diuji untuk pemeriksaan homogenitas adalah\n\n$$\n\\begin{aligned}\nH_{0} &: \\text{ragam homogen antar perlakukan} \\\\\nH_{1} &: \\text{ragam tidak homogen antar perlakuan}\n\\end{aligned}\n$$\n\n\nUji Homogenitas bisa dilakukan dengan beberapa metode pengujian dibawah ini\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bartlett (asumsi residual menyebar normal)\ncheck_homogeneity(anova1,method=\"bartlett\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWarning: Variances differ between groups (Bartlett Test, p = 0.000).\n```\n:::\n\n```{.r .cell-code}\n# Fligner (merupakan uji nonparametrik)\ncheck_homogeneity(anova1,method=\"fligner\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWarning: Variances differ between groups (Fligner-Killeen Test, p = 0.006).\n```\n:::\n:::\n\n\nkarena p-value yang dihasilkan dari uji homogenitas kurang dari 0.05 maka $H_{0}$ ditolak atau dengan kata lain **ragam tidak homogen antar perlakukan**\n\n\n### Independent\n\n#### Grafik\n\nPemeriksaan Independent bisa dilakukan dengan menggunakan grafik.\n\nuntuk menampilkan grafik dibawah ini menggunakan package `ggpubr` \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naug1 %>%                    \n  mutate(order=seq(nrow(aug1))) %>% \n  ggscatter(x=\"order\",y=\".resid\")+\n  theme_lucid()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\nDari grafik ini, tidak terbentuk pola tertentu (misal pola linear) maka diduga bahwa asumsi Independent dipenuhi.\n\n\n## Penanganan Pelanggaran Asumsi\n\n### Transformasi Box-cox\n\nTransformasi Box-Cox didefinisikan sebagai\n\n$$\n\\begin{equation}\ny^{(\\lambda)} = \n\\begin{cases}\n  \\frac{y^{\\lambda}-1}{\\lambda} & \\text{untuk} \\space \\lambda\\neq 0  \\\\\n  \\ln{(y)} & \\text{untuk} \\space \\lambda= 0  \\\\\n\\end{cases}\n\\end{equation}\n$$\n\nuntuk mendapatkan nilai $\\lambda$ optimal dapat digunakan pendugaan  MLE, yaitu dengan mendapatkan nilai $\\lambda$ yang memaksimumkan fungsi log-likelihood. Hal ini bisa dilihat pada grafik yang diperoleh dari fungsi `boxCox` pada package `car`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxCox(anova1)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nBerdasarkan gambar diketahui bahwa nilai lambda yang optimum ada disekitar nol. Oleh karena itu kita bisa langsung memakai $\\lambda = 0$.\n\nCara lain untuk mendapatkan nilai lambda optimum adalah dengan menggunakan fungsi `powerTransform` dari package `car` yang menampilkan hasil pendugaan titik (point estimate), selang kepercayaan dan uji hipotesis dengan Likelihood Ratio Test (LRT) dari $\\lambda$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxcox_res <-powerTransform(anova1) \nsummary(boxcox_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nbcPower Transformation to Normality \n   Est Power Rounded Pwr Wald Lwr Bnd Wald Upr Bnd\nY1    0.0101           0       -0.094       0.1141\n\nLikelihood ratio test that transformation parameter is equal to 0\n (log transformation)\n                             LRT df    pval\nLR test, lambda = (0) 0.03612792  1 0.84925\n\nLikelihood ratio test that no transformation is needed\n                           LRT df       pval\nLR test, lambda = (1) 110.0337  1 < 2.22e-16\n```\n:::\n\n```{.r .cell-code}\n# pembulatan pada lambda\nboxcox_res$roundlam\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nY1 \n 0 \n```\n:::\n:::\n\n\nBerdasarkan output nya didapatkan bahwa \n\n1. penduga titik nya $\\lambda=0.0101$ atau dibulatkan menjadi $\\lambda=0$.\n2. selang kepercayaan $-0.094 \\leq \\lambda \\leq 0.1141$\n3. Untuk uji hipotesis yang pertama (Log Transformation)\n\n$$\n\\begin{aligned}\nH_{0} &: \\lambda = 0 \\space \\\\\nH_{1} &: \\lambda \\neq 0 \n\\end{aligned}\n$$\n\nkarena p-value dari uji yang pertama besar (lebih dari 0.05) maka tidak tolak $H_{0}$ atau dengan kata lain kita bisa menggunakan $\\lambda=0$\n4. Untuk uji hipotesis yang kedua (no transformation)\n\n\n$$\n\\begin{aligned}\nH_{0} &: \\lambda = 1 \\space \\\\\nH_{1} &: \\lambda \\neq 1\n\\end{aligned}\n$$\n\nkarena p-value dari uji yang pertama kecil (kurang dari 0.05) maka tolak $H_{0}$ atau dengan kata lain kita bisa menggunakan $\\lambda \\neq 1$. Nilai $\\lambda \\neq 1$ implikasinya ada transformasi dan nilai $\\lambda = 1$ implikasinya tidak dibutuhkan transformasi.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbahan_isolasi_trans <- bahan_isolasi %>% \n                        mutate(WaktuKegagalan_Trans =bcPower(WaktuKegagalan,boxcox_res$roundlam))\n\nanova2 <- aov(WaktuKegagalan_Trans ~ Bahan,data = bahan_isolasi_trans)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(anova2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 6\n  term         df sumsq meansq statistic      p.value\n  <chr>     <dbl> <dbl>  <dbl>     <dbl>        <dbl>\n1 Bahan         4 165.   41.3       37.7  0.000000118\n2 Residuals    15  16.4   1.10      NA   NA          \n```\n:::\n:::\n\n\n\n### Pemeriksaan kembali Asumsi ANOVA\n\nPemeriksaan asumsi ANOVA dilakukan pada residual nya. Untuk mengeluarkan residualnya bisa menggunakan sintaks dibawah ini\n\n\n::: {.cell}\n\n```{.r .cell-code}\naug2 <- augment(anova2)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naug2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 20 × 8\n   WaktuKegagalan_Trans Bahan .fitted   .resid  .hat .sigma   .cooksd .std.resid\n                  <dbl> <chr>   <dbl>    <dbl> <dbl>  <dbl>     <dbl>      <dbl>\n 1                4.70  A        5.05 -0.351    0.25  1.08    1.00e-2   -0.387  \n 2                5.06  A        5.05  0.00465  0.25  1.08    1.76e-6    0.00513\n 3                5.27  A        5.05  0.216    0.25  1.08    3.79e-3    0.239  \n 4                5.18  A        5.05  0.130    0.25  1.08    1.37e-3    0.144  \n 5                0     B        1.24 -1.24     0.25  1.01    1.25e-1   -1.37   \n 6                0.693 B        1.24 -0.549    0.25  1.07    2.45e-2   -0.606  \n 7                1.39  B        1.24  0.144    0.25  1.08    1.68e-3    0.159  \n 8                2.89  B        1.24  1.65     0.25  0.957   2.20e-1    1.82   \n 9                6.78  C        7.72 -0.936    0.25  1.04    7.11e-2   -1.03   \n10                7.14  C        7.72 -0.581    0.25  1.07    2.74e-2   -0.641  \n11                8.57  C        7.72  0.855    0.25  1.05    5.92e-2    0.943  \n12                8.38  C        7.72  0.663    0.25  1.06    3.56e-2    0.731  \n13                6.20  D        8.21 -2.01     0.25  0.889   3.28e-1   -2.22   \n14                8.86  D        8.21  0.645    0.25  1.07    3.38e-2    0.712  \n15                8.58  D        8.21  0.363    0.25  1.08    1.07e-2    0.400  \n16                9.22  D        8.21  1.00     0.25  1.04    8.13e-2    1.10   \n17                1.95  E        1.90  0.0420   0.25  1.08    1.43e-4    0.0463 \n18                1.61  E        1.90 -0.295    0.25  1.08    7.04e-3   -0.325  \n19                3.37  E        1.90  1.46     0.25  0.985   1.74e-1    1.61   \n20                0.693 E        1.90 -1.21     0.25  1.02    1.19e-1   -1.34   \n```\n:::\n:::\n\n\n\n### Normalitas (Galat Menyebar Normal)\n\nPemeriksaan Normalitas bisa dilakukan dengan menggunakan grafik atau uji hipotesis.\n\n\n#### Grafik\n\nuntuk menampilkan grafik dibawah ini terlebih dahulu harus memanggil package `performance` dan `see`\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(check_normality(x = anova2),type=\"qq\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nDari grafik ini, titik-titik residual yang engikuti pola garis dan berada di dalam daerah selang kepercayaan maka diduga bahwa asumsi normalitas terpenuhi.\n\n#### Uji Hipotesis\n\nHipotesis yang diuji untuk pemeriksaan normalitas adalah\n\n$$\n\\begin{aligned}\nH_{0} &: \\text{galat menyebar normal} \\\\\nH_{1} &: \\text{galat tidak menyebar normal}\n\\end{aligned}\n$$\n\nUji Normalitas bisa dilakukan dengan beberapa metode pengujian. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nnormal_test(data = aug2,\n            variable = \".resid\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                name statistic p.value\n1   Anderson-Darling     0.137   0.971\n2 Kolmogorov-Smirnov     0.102   0.972\n3       Shapiro-Wilk     0.259   0.878\n4        Jarque-Bera     0.986   0.987\n```\n:::\n:::\n\n\n\nkarena p-value yang dihasilkan dari uji normalitas lebih besar dari 0.05 maka $H_{0}$ tidak ditolak atau dengan kata lain **galat menyebar normal**\n\n### Homogenitas\n\nPemeriksaan Homogenitas bisa dilakukan dengan menggunakan grafik atau uji hipotesis.\n\n\n#### Grafik\n\nuntuk menampilkan grafik dibawah ini menggunakan package `ggpubr` \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggscatter(data = aug2,\n                  x=\".fitted\",\n                  y=\".resid\")+\n  geom_hline(aes(yintercept=0)) +\n  theme_lucid()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\nDari grafik ini, tidak terdapat pola berbentuk corong (funnel shape) maka diduga bahwa asumsi homogenitas terpenuhi.\n\n#### Uji Hipotesis\n\nHipotesis yang diuji untuk pemeriksaan homogenitas adalah\n\n$$\n\\begin{aligned}\nH_{0} &: \\text{ragam homogen antar perlakukan} \\\\\nH_{1} &: \\text{ragam tidak homogen antar perlakuan}\n\\end{aligned}\n$$\n\n\nUji Homogenitas bisa dilakukan dengan beberapa metode pengujian dibawah ini\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bartlett (asumsi residual menyebar normal)\ncheck_homogeneity(anova2,method=\"bartlett\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOK: There is not clear evidence for different variances across groups (Bartlett Test, p = 0.211).\n```\n:::\n\n```{.r .cell-code}\n# Fligner (merupakan uji nonparametrik)\ncheck_homogeneity(anova2,method=\"fligner\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOK: There is not clear evidence for different variances across groups (Fligner-Killeen Test, p = 0.351).\n```\n:::\n:::\n\n\nkarena p-value yang dihasilkan dari uji homogenitas lebih besar dari 0.05 maka $H_{0}$ tidak ditolak atau dengan kata lain **ragam homogen antar perlakukan**\n\n\n### Independent\n\n#### Grafik\n\nPemeriksaan Independent bisa dilakukan dengan menggunakan grafik.\n\nuntuk menampilkan grafik dibawah ini menggunakan package `ggpubr` \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naug2 %>%                    \n  mutate(order=seq(nrow(aug1))) %>% \n  ggscatter(x=\"order\",y=\".resid\")+\n  theme_lucid()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\nDari grafik ini, tidak terbentuk pola tertentu (misal pola linear) maka diduga bahwa asumsi Independent dipenuhi.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}